CREATE TABLE countries (
  id INTEGER PRIMARY KEY,
  name VARCHAR
);

INSERT INTO countries VALUES (1, 'Afghanistan');
INSERT INTO countries VALUES (2, 'Albania');
INSERT INTO countries VALUES (3, 'Algeria');
INSERT INTO countries VALUES (4, 'American Samoa');
INSERT INTO countries VALUES (5, 'Andorra');
INSERT INTO countries VALUES (6, 'Angola');
INSERT INTO countries VALUES (7, 'Anguilla');
INSERT INTO countries VALUES (8, 'Antarctica');
INSERT INTO countries VALUES (9, 'Antigua and Barbuda');
INSERT INTO countries VALUES (10, 'Argentina');
INSERT INTO countries VALUES (11, 'Armenia');
INSERT INTO countries VALUES (12, 'Armenia');
INSERT INTO countries VALUES (13, 'Aruba');
INSERT INTO countries VALUES (14, 'Australia');
INSERT INTO countries VALUES (15, 'Austria');
INSERT INTO countries VALUES (16, 'Azerbaijan');
INSERT INTO countries VALUES (17, 'Azerbaijan');
INSERT INTO countries VALUES (18, 'Bahamas');
INSERT INTO countries VALUES (19, 'Bahrain');
INSERT INTO countries VALUES (20, 'Bangladesh');
INSERT INTO countries VALUES (21, 'Barbados');
INSERT INTO countries VALUES (22, 'Belarus');
INSERT INTO countries VALUES (23, 'Belgium');
INSERT INTO countries VALUES (24, 'Belize');
INSERT INTO countries VALUES (25, 'Benin');
INSERT INTO countries VALUES (26, 'Bermuda');
INSERT INTO countries VALUES (27, 'Bhutan');
INSERT INTO countries VALUES (28, 'Bolivia');
INSERT INTO countries VALUES (29, 'Bosnia and Herzegovina');
INSERT INTO countries VALUES (30, 'Botswana');
INSERT INTO countries VALUES (31, 'Bouvet Island');
INSERT INTO countries VALUES (32, 'Brazil');
INSERT INTO countries VALUES (33, 'British Indian Ocean Territory');
INSERT INTO countries VALUES (34, 'Brunei Darussalam');
INSERT INTO countries VALUES (35, 'Bulgaria');
INSERT INTO countries VALUES (36, 'Burkina Faso');
INSERT INTO countries VALUES (37, 'Burundi');
INSERT INTO countries VALUES (38, 'Cambodia');
INSERT INTO countries VALUES (39, 'Cameroon');
INSERT INTO countries VALUES (40, 'Canada');
INSERT INTO countries VALUES (41, 'Cape Verde');
INSERT INTO countries VALUES (42, 'Cayman Islands');
INSERT INTO countries VALUES (43, 'Central African Republic');
INSERT INTO countries VALUES (44, 'Chad');
INSERT INTO countries VALUES (45, 'Chile');
INSERT INTO countries VALUES (46, 'China');
INSERT INTO countries VALUES (47, 'Christmas Island');
INSERT INTO countries VALUES (48, 'Cocos INSERT INTO countries VALUES (Keeling) Islands');
INSERT INTO countries VALUES (49, 'Colombia');
INSERT INTO countries VALUES (50, 'Comoros');
INSERT INTO countries VALUES (51, 'Congo');
INSERT INTO countries VALUES (52, 'Congo, The Democratic Republic of The');
INSERT INTO countries VALUES (53, 'Cook Islands');
INSERT INTO countries VALUES (54, 'Costa Rica');
INSERT INTO countries VALUES (55, 'Cote D''ivoire');
INSERT INTO countries VALUES (56, 'Croatia');
INSERT INTO countries VALUES (57, 'Cuba');
INSERT INTO countries VALUES (58, 'Cyprus');
INSERT INTO countries VALUES (60, 'Czech Republic');
INSERT INTO countries VALUES (61, 'Denmark');
INSERT INTO countries VALUES (62, 'Djibouti');
INSERT INTO countries VALUES (63, 'Dominica');
INSERT INTO countries VALUES (64, 'Dominican Republic');
INSERT INTO countries VALUES (65, 'Easter Island');
INSERT INTO countries VALUES (66, 'Ecuador');
INSERT INTO countries VALUES (67, 'Egypt');
INSERT INTO countries VALUES (68, 'El Salvador');
INSERT INTO countries VALUES (69, 'Equatorial Guinea');
INSERT INTO countries VALUES (70, 'Eritrea');
INSERT INTO countries VALUES (71, 'Estonia');
INSERT INTO countries VALUES (72, 'Ethiopia');
INSERT INTO countries VALUES (73, 'Falkland Islands INSERT INTO countries VALUES (Malvinas)');
INSERT INTO countries VALUES (74, 'Faroe Islands');
INSERT INTO countries VALUES (75, 'Fiji');
INSERT INTO countries VALUES (76, 'Finland');
INSERT INTO countries VALUES (77, 'France');
INSERT INTO countries VALUES (78, 'French Guiana');
INSERT INTO countries VALUES (79, 'French Polynesia');
INSERT INTO countries VALUES (80, 'French Southern Territories');
INSERT INTO countries VALUES (81, 'Gabon');
INSERT INTO countries VALUES (82, 'Gambia');
INSERT INTO countries VALUES (83, 'Georgia');
INSERT INTO countries VALUES (85, 'Germany');
INSERT INTO countries VALUES (86, 'Ghana');
INSERT INTO countries VALUES (87, 'Gibraltar');
INSERT INTO countries VALUES (88, 'Greece');
INSERT INTO countries VALUES (89, 'Greenland');
INSERT INTO countries VALUES (91, 'Grenada');
INSERT INTO countries VALUES (92, 'Guadeloupe');
INSERT INTO countries VALUES (93, 'Guam');
INSERT INTO countries VALUES (94, 'Guatemala');
INSERT INTO countries VALUES (95, 'Guinea');
INSERT INTO countries VALUES (96, 'Guinea-bissau');
INSERT INTO countries VALUES (97, 'Guyana');
INSERT INTO countries VALUES (98, 'Haiti');
INSERT INTO countries VALUES (99, 'Heard Island and Mcdonald Islands');
INSERT INTO countries VALUES (100, 'Honduras');
INSERT INTO countries VALUES (101, 'Hong Kong');
INSERT INTO countries VALUES (102, 'Hungary');
INSERT INTO countries VALUES (103, 'Iceland');
INSERT INTO countries VALUES (104, 'India');
INSERT INTO countries VALUES (105, 'Indonesia');
INSERT INTO countries VALUES (106, 'Indonesia');
INSERT INTO countries VALUES (107, 'Iran');
INSERT INTO countries VALUES (108, 'Iraq');
INSERT INTO countries VALUES (109, 'Ireland');
INSERT INTO countries VALUES (110, 'Israel');
INSERT INTO countries VALUES (111, 'Italy');
INSERT INTO countries VALUES (112, 'Jamaica');
INSERT INTO countries VALUES (113, 'Japan');
INSERT INTO countries VALUES (114, 'Jordan');
INSERT INTO countries VALUES (115, 'Kazakhstan');
INSERT INTO countries VALUES (116, 'Kazakhstan');
INSERT INTO countries VALUES (117, 'Kenya');
INSERT INTO countries VALUES (118, 'Kiribati');
INSERT INTO countries VALUES (119, 'Korea, North');
INSERT INTO countries VALUES (120, 'Korea, South');
INSERT INTO countries VALUES (121, 'Kosovo');
INSERT INTO countries VALUES (122, 'Kuwait');
INSERT INTO countries VALUES (123, 'Kyrgyzstan');
INSERT INTO countries VALUES (124, 'Laos');
INSERT INTO countries VALUES (125, 'Latvia');
INSERT INTO countries VALUES (126, 'Lebanon');
INSERT INTO countries VALUES (127, 'Lesotho');
INSERT INTO countries VALUES (128, 'Liberia');
INSERT INTO countries VALUES (129, 'Libyan Arab Jamahiriya');
INSERT INTO countries VALUES (130, 'Liechtenstein');
INSERT INTO countries VALUES (131, 'Lithuania');
INSERT INTO countries VALUES (132, 'Luxembourg');
INSERT INTO countries VALUES (133, 'Macau');
INSERT INTO countries VALUES (134, 'Macedonia');
INSERT INTO countries VALUES (135, 'Madagascar');
INSERT INTO countries VALUES (136, 'Malawi');
INSERT INTO countries VALUES (137, 'Malaysia');
INSERT INTO countries VALUES (138, 'Maldives');
INSERT INTO countries VALUES (139, 'Mali');
INSERT INTO countries VALUES (140, 'Malta');
INSERT INTO countries VALUES (141, 'Marshall Islands');
INSERT INTO countries VALUES (142, 'Martinique');
INSERT INTO countries VALUES (143, 'Mauritania');
INSERT INTO countries VALUES (144, 'Mauritius');
INSERT INTO countries VALUES (145, 'Mayotte');
INSERT INTO countries VALUES (146, 'Mexico');
INSERT INTO countries VALUES (147, 'Micronesia, Federated States of');
INSERT INTO countries VALUES (148, 'Moldova, Republic of');
INSERT INTO countries VALUES (149, 'Monaco');
INSERT INTO countries VALUES (150, 'Mongolia');
INSERT INTO countries VALUES (151, 'Montenegro');
INSERT INTO countries VALUES (152, 'Montserrat');
INSERT INTO countries VALUES (153, 'Morocco');
INSERT INTO countries VALUES (154, 'Mozambique');
INSERT INTO countries VALUES (155, 'Myanmar');
INSERT INTO countries VALUES (156, 'Namibia');
INSERT INTO countries VALUES (157, 'Nauru');
INSERT INTO countries VALUES (158, 'Nepal');
INSERT INTO countries VALUES (159, 'Netherlands');
INSERT INTO countries VALUES (160, 'Netherlands Antilles');
INSERT INTO countries VALUES (161, 'New Caledonia');
INSERT INTO countries VALUES (162, 'New Zealand');
INSERT INTO countries VALUES (163, 'Nicaragua');
INSERT INTO countries VALUES (164, 'Niger');
INSERT INTO countries VALUES (165, 'Nigeria');
INSERT INTO countries VALUES (166, 'Niue');
INSERT INTO countries VALUES (167, 'Norfolk Island');
INSERT INTO countries VALUES (168, 'Northern Mariana Islands');
INSERT INTO countries VALUES (169, 'Norway');
INSERT INTO countries VALUES (170, 'Oman');
INSERT INTO countries VALUES (171, 'Pakistan');
INSERT INTO countries VALUES (172, 'Palau');
INSERT INTO countries VALUES (173, 'Palestinian Territory');
INSERT INTO countries VALUES (174, 'Panama');
INSERT INTO countries VALUES (175, 'Papua New Guinea');
INSERT INTO countries VALUES (176, 'Paraguay');
INSERT INTO countries VALUES (177, 'Peru');
INSERT INTO countries VALUES (178, 'Philippines');
INSERT INTO countries VALUES (179, 'Pitcairn');
INSERT INTO countries VALUES (180, 'Poland');
INSERT INTO countries VALUES (181, 'Portugal');
INSERT INTO countries VALUES (182, 'Puerto Rico');
INSERT INTO countries VALUES (183, 'Qatar');
INSERT INTO countries VALUES (184, 'Reunion');
INSERT INTO countries VALUES (185, 'Romania');
INSERT INTO countries VALUES (186, 'Russia');
INSERT INTO countries VALUES (187, 'Russia');
INSERT INTO countries VALUES (188, 'Rwanda');
INSERT INTO countries VALUES (189, 'Saint Helena');
INSERT INTO countries VALUES (190, 'Saint Kitts and Nevis');
INSERT INTO countries VALUES (191, 'Saint Lucia');
INSERT INTO countries VALUES (192, 'Saint Pierre and Miquelon');
INSERT INTO countries VALUES (193, 'Saint Vincent and The Grenadines');
INSERT INTO countries VALUES (194, 'Samoa');
INSERT INTO countries VALUES (195, 'San Marino');
INSERT INTO countries VALUES (196, 'Sao Tome and Principe');
INSERT INTO countries VALUES (197, 'Saudi Arabia');
INSERT INTO countries VALUES (198, 'Senegal');
INSERT INTO countries VALUES (199, 'Serbia and Montenegro');
INSERT INTO countries VALUES (200, 'Seychelles');
INSERT INTO countries VALUES (201, 'Sierra Leone');
INSERT INTO countries VALUES (202, 'Singapore');
INSERT INTO countries VALUES (203, 'Slovakia');
INSERT INTO countries VALUES (204, 'Slovenia');
INSERT INTO countries VALUES (205, 'Solomon Islands');
INSERT INTO countries VALUES (206, 'Somalia');
INSERT INTO countries VALUES (207, 'South Africa');
INSERT INTO countries VALUES (208, 'South Georgia and The South Sandwich Islands');
INSERT INTO countries VALUES (209, 'Spain');
INSERT INTO countries VALUES (210, 'Sri Lanka');
INSERT INTO countries VALUES (211, 'Sudan');
INSERT INTO countries VALUES (212, 'Suriname');
INSERT INTO countries VALUES (213, 'Svalbard and Jan Mayen');
INSERT INTO countries VALUES (214, 'Swaziland');
INSERT INTO countries VALUES (215, 'Sweden');
INSERT INTO countries VALUES (216, 'Switzerland');
INSERT INTO countries VALUES (217, 'Syria');
INSERT INTO countries VALUES (218, 'Taiwan');
INSERT INTO countries VALUES (219, 'Tajikistan');
INSERT INTO countries VALUES (220, 'Tanzania, United Republic of');
INSERT INTO countries VALUES (221, 'Thailand');
INSERT INTO countries VALUES (222, 'Timor-leste');
INSERT INTO countries VALUES (223, 'Togo');
INSERT INTO countries VALUES (224, 'Tokelau');
INSERT INTO countries VALUES (225, 'Tonga');
INSERT INTO countries VALUES (226, 'Trinidad and Tobago');
INSERT INTO countries VALUES (227, 'Tunisia');
INSERT INTO countries VALUES (228, 'Turkey');
INSERT INTO countries VALUES (229, 'Turkey');
INSERT INTO countries VALUES (230, 'Turkmenistan');
INSERT INTO countries VALUES (231, 'Turks and Caicos Islands');
INSERT INTO countries VALUES (232, 'Tuvalu');
INSERT INTO countries VALUES (233, 'Uganda');
INSERT INTO countries VALUES (234, 'Ukraine');
INSERT INTO countries VALUES (235, 'United Arab Emirates');
INSERT INTO countries VALUES (236, 'United Kingdom');
INSERT INTO countries VALUES (237, 'United States');
INSERT INTO countries VALUES (238, 'United States Minor Outlying Islands');
INSERT INTO countries VALUES (239, 'Uruguay');
INSERT INTO countries VALUES (240, 'Uzbekistan');
INSERT INTO countries VALUES (241, 'Vanuatu');
INSERT INTO countries VALUES (242, 'Vatican City');
INSERT INTO countries VALUES (243, 'Venezuela');
INSERT INTO countries VALUES (244, 'Vietnam');
INSERT INTO countries VALUES (245, 'Virgin Islands, British');
INSERT INTO countries VALUES (246, 'Virgin Islands, U.S.');
INSERT INTO countries VALUES (247, 'Wallis and Futuna');
INSERT INTO countries VALUES (248, 'Western Sahara');
INSERT INTO countries VALUES (249, 'Yemen');
INSERT INTO countries VALUES (250, 'Yemen');
INSERT INTO countries VALUES (251, 'Zambia');
INSERT INTO countries VALUES (252, 'Zimbabwe');
